### ISSUE TITLE
V6.2.0

### ISSUE THREAD

**Issue by h2oonstone** [j26design/SEO-for-Webpages#1]
It's adding that extra /artisan-distro file to my url...
http://h2oonstone.com/artisan-distro/assets/fox.jpg

![screen shot 2016-05-23 at 3 41 06 pm](https://cloud.githubusercontent.com/assets/19439377/15482312/f0088d10-20fc-11e6-876d-a3ec787f265d.png)
![screen shot 2016-05-23 at 3 41 47 pm](https://cloud.githubusercontent.com/assets/19439377/15482320/f5b62e2a-20fc-11e6-82a6-9bc05f94c376.png)

**Comment by jp26jp** [comment]
That's really weird. This must be a Muse bug. Would you mind uploading the [Muse file here](https://www.dropbox.com/request/ua5xxdu0sLmoev2AowsD).

**Comment by h2oonstone** [comment]
Sure - uploading!

**Comment by jp26jp** [comment]
I took a look at the file and I see the issue you're talking about. This is definitely a Muse bug because the image is using the URL that Muse provides. I'm contacting the devs to see what's going on.

**Comment by jp26jp** [comment]
Was this Muse site exported with the artisan-distro at some point? I'm just trying to figure out what is causing the bug.

**Comment by h2oonstone** [comment]
I don’t know what 'artisan-bistro is'. So no, it was not knowingly exported with this.

It is the same file name that showed up in that other bug - the one on the the SEO Master-Page-Premium that you fixed a couple days ago.

The only possible idea is, is that this site was made from a template called Artisan from MuseThemes - but I can’t find any instance of this name 'artisan-bistro' in the muse file.

**Comment by jp26jp** [comment]
That's really weird. Helpful, but confusing. I'll let you know when I have more

**Comment by h2oonstone** [comment]
Thanks!

**Comment by jp26jp** [comment]
I found a temporary work-around. If you publish the site to a temporary BC site, it will reset the URL and remove that extra subfolder. Once you do that, you'll be able to export/upload the site and it will go to the correct folder.

**Comment by h2oonstone** [comment]
Uploaded to a temp BC, Re-loaded to my host, Deleted my temp BC.
And it tests out fine! Thanks

**Comment by jp26jp** [comment]
Awesome! I'll leave this issue open until I hear back from the muse team

**Comment by jp26jp** [comment]
This bug will be fixed in Muse's next public release.
