### ISSUE TITLE
SEO WIDGETS Feature Request

### ISSUE THREAD

**Issue by joereplicator** [j26design/SEO-for-Webpages#12]
Hello John R. Perry!

I'm not sure if you have seen or experienced the wonderful integration and time savings that occurs when you marry Muse widgets with Google Sheets.  The user time savings is off the charts! 

I would encourage you to R&D this ASAP as I strongly believe that anything that saves time adds major value. 

Imagine using a spreadsheet to list the page name in one column then everything pertinent to that page name in the same row. 

Imagine not having to open and close the widget for every little tidbit of information you need to put in it. 

If you want to get a better idea of what I'm talking about please visit Muse Themes and check out any of their "Connect" series widgets.  You'll get the idea. 

Hope you can make it happen because it would be amazingly AWESOME!

Thanks!
Joe Bates
435-627-7007

**Comment by jp26jp** [comment]
Muse widgets uses ajax and ajax generated seo cannot yet be picked up by search engines. Though I agree that this would be an awesome feature, it would not yet work.

**Comment by joereplicator** [comment]
Hey John,

Thank you for getting back to me. That's a real bummer you can't fetch the
data from Google Sheets into your SEO widgets. I wonder how Muse Themes is
able to do that. Anyway, I really don't understand the problem with the
Ajax but then I'm not a coder.

*By the way. I just learned that I'm having some conflicts with your SEO
widgets *and some icon animation widgets I'm using in my menu system. They
are showing just a frame or square or nothing at all.

It's also causing some weird stuff to happen at the top of the screen when
you scroll down.

Lastly, check the social icon widget in the footer.

This has really got me bummed out. Any ideas on how to fix this? Would it
help if I shared the file with you??

Below is a link to this redo of an existing site that will demonstrate the
trouble. FYI I'm still deciding on how I'm going to do a few things. The
main things I wanted to do was to reduce the size of the header, just have
one page for the photo gallery, and redo the landing page. also went from
fluid to fixed, and cleaned up some of the text tags.

Existing site URL:  https://www.beehivelearningacademy.com
Rework site:  http://blatest01.businesscatalyst.com/index.html

My redo site uses a different master so you'll need to navigate to another
page. I recommend one of the program pages to see the problems. Your
widgets are only applied to the main master and an essentials to the home
page.

Thank you in advance for taking a look at this!!

Joe

**Comment by jp26jp** [comment]
> Thank you for getting back to me. That's a real bummer you can't fetch the data from Google Sheets into your SEO widgets. I wonder how Muse Themes is able to do that.

I didn't say that I wasn't able to do it. I said that Google doesn't accept rich snippets that are generated by ajax yet. Even if they did, however, Facebook and Twitter show no signs of accepting that type of SEO anytime soon. Muse Themes uses ajax which is fine because they aren't using ajax to generate SEO.

All icons seem to be working on the page of both sites.

**Comment by joereplicator** [comment]
Ah, so you're saying that MT uses Ajax to fetch data from Google and that
would prevent the widget from creating the code in a format that would
work?  Sorry, I'm just trying to understand. You don't have to answer this
if you don't want to.

Below is what I really need your help with. Thanks!

This is what's happening on all my menu pages using the Master with your
SEO widgets:

[image: Inline image 1]

[image: Inline image 2]
[image: Inline image 3]

**Comment by joereplicator** [comment]
Any ideas on what's going on  / how to fix yet ??

**Comment by jp26jp** [comment]
There's nothing in those images.

**Comment by joereplicator** [comment]
Humm.... Maybe better we talk. Might go faster.

I just left a voicemail for you but here's my #:  435-627-7007 / 3004.

Thanks!
