### ISSUE TITLE
Unable to render Card preview

### ISSUE THREAD

**Issue by StoneDesign** [j26design/SEO-for-Webpages#2]
I'm getting this error message - can you help please?
Log
INFO:  Page fetched successfully
INFO:  17 metatags were found
INFO:  twitter:card = summary_large_image tag found
ERROR: Required meta tag missing (twitter:text:description)

Thanks in advance

**Comment by jp26jp** [comment]
Can you send me your [muse](https://www.dropbox.com/request/ua5xxdu0sLmoev2AowsD) file

**Comment by jp26jp** [comment]
I just checked your website (http://saltwater-stone.com/) and it validated with everything. Would you mind trying again?

**Comment by StoneDesign** [comment]
Thanks very much, will do.

tara
