### ISSUE TITLE
Performance dates

### ISSUE THREAD

**Issue by jsteveross** [j26design/SEO-for-Webpages#3]
Thank you so much for this amazing widget.  I am trying to figure out how I could add multiple performance dates for the run of show in schema.  Think this would be a great thing to have for Theatre, Movie, Events. 
Amazing Widget!!

**Comment by jp26jp** [comment]
I agree! I will get to work on it!

**Comment by jsteveross** [comment]
cool
looking forward 
example:  we run shows tuesday-saturday at 8pm, matinees on wednesday and sunday at 2 and sundays at 7pm
also: under entertainment category - is there a 'live performance' sub-category that can exist?  it would be generic enough to include theatre, concerts, stand-up...
thanks again

**Comment by jp26jp** [comment]
Alright, here it is: https://www.j-26.com/seo/google-rich-cards/event/

**Comment by jsteveross** [comment]
Amazing!!!!
i will put it up this weekend and report back
thank you so much

Steve Ross

**Comment by jsteveross** [comment]
HI John

I have the EVENTS Rich Cards installed on our Muse Site and it is uploaded.  But this is what I see on Google:

**Comment by jsteveross** [comment]
One more thing 

It appears the SiteMap is not being recognized by Google - I am trying to use the Google Data Highlighter and it cannot see my web pages other than the home page.   Says I don’t have a sitemap.

**Comment by jsteveross** [comment]
One very last thing - if this can help

The Rich Cards that I did using your widget are showing up in the STRUCTURED DATA in GOOGLE SEARCH CONSOLE but not as Rich Cards “Events”

**Comment by jp26jp** [comment]
This isn't a SEO for Webpages widget. [Follow up with the event widget over here](https://github.com/j26design/Event/issues/1)

**Comment by jsteveross** [comment]
Quick question

Sitemaps I read are supposed to be in the directory /public_html/
but the widget places it in the Assetts

So I end up having one in each.  

If you can let me know what to do.

Thanks

**Comment by jsteveross** [comment]
Hi John

https://centaurtheatre.com

So I believe to have followed all instructions and recreated the info on the widgets.
Pointing the site to only handle https://centaurtheatre.com without any www
But the rich cards are not appearing and Google does not recognize them.

The site map is up-to-date
Fetch as Google reports all good
Structure date showing only 2 pages whereas TheatreEvent (markup: schema.org) should be showing 9 pages.
No Site Errors

Thanks 

Steve

**Comment by jp26jp** [comment]
Can you add me to the property again?

Also, the sitemap doesn't need to be in the root directory. Just changed the location of the sitemap to `assets/sitemap.xml`

**Comment by jp26jp** [comment]
Also, your site can still be accessed via www. You need to make it redirect all www. pages. [You can see how to do that here](https://www.j-26.com/blog/how-to-redirect-to-or-away-from-www/#https-and-non-www).

**Comment by jsteveross** [comment]
I just added you back in 

Sitemap points to /assets/sitemap.xml

Trying to figure out how to point to non-www  (google is not user friendly for your average person.).

**Comment by jsteveross** [comment]
Fixed

**Comment by jp26jp** [comment]
Sorry, I don't know how this convo picked up over here. Meet me at the [correct issue](https://github.com/j26design/Event/issues/1), haha
