### ISSUE TITLE
Cart counter V1.36 issue

### ISSUE THREAD

**Issue by HDRSky360** [j26design/SEO-for-Webpages#6]
The cart counter doesn't work anymore on my 2 computers, on 2 different projects.
The error message is :
"The store cannot be load in your browser because of some JavaScripy errors ...
Error : unknown runtime error"
![bug-cartcounter](https://cloud.githubusercontent.com/assets/24841434/23040131/7a695ce8-f490-11e6-98b5-cf4a1f944f73.PNG)
Same thing for ecwid storefront : 
![capture](https://cloud.githubusercontent.com/assets/24841434/23040179/a46eb93e-f490-11e6-8730-59cf6c18fa34.PNG)

**Comment by jp26jp** [comment]
This is for the SEO for Webpages widget. Follow up with the Ecwid (Premium) [issue here](https://github.com/j26design/Ecwid-Premium/issues/64)
