### ISSUE TITLE
Not able to change location Social Media Preview Image

### ISSUE THREAD

**Issue by ferdesignnl** [j26design/SEO-for-Webpages#7]
When I insert a picture from local drive to Social Media Preview Image, it automatically excpects this pic is in the root of my domain.

So it searches for the file @ domain.com/assets/
Though, I have several sites on this domain to include different languages like:
domain.com/en , domain.com/de , domain.com/es , etc.

My Social Media Preview Image is located in domain.com/en/assets for ex.

This way Sharing Debugger of Facebook giving the error, the file is too big or too small, but actually it's missing the picture.

Can you make it so, that we can insert the url where this pic is located?

**Comment by jp26jp** [comment]
It's not an issue with the widget, it's an issue with Muse. What's your URL?

**Comment by ferdesignnl** [comment]
My url would be https://fakinthefunk.net/en/assets/fakinthefunk-social-media-preview.png

 

Muse/Widget goes to https://fakinthefunk.net/assets/fakinthefunk-social-media-preview.png

Which I made manually on the server, after tracing this issue.

 

 

Van: John R Perry [mailto:notifications@github.com] 
Verzonden: donderdag 9 maart 2017 23:29
Aan: j26design/SEO-for-Webpages <SEO-for-Webpages@noreply.github.com>
CC: ferdesignnl <info@ferdesign.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [j26design/SEO-for-Webpages] Not able to change location Social Media Preview Image (#7)

 

It's not an issue with the widget, it's an issue with Muse. What's your URL?

**Comment by jp26jp** [comment]
Need the issue of the URL causing the issue.

**Comment by ferdesignnl** [comment]
Can you be more specific?
i have  sent u 2 different urls.

One is refering to where the widget or muse is telling it should be. /assets 

Other one where it is  Located when exporting muse to html. en/assets




Op 10 maart 2017 00:12:49 +01:00, schreef John R Perry <notifications@github.com>:

**Comment by jp26jp** [comment]
You sent me 2 links to images and I'm assuming that you didn't test a link to an image in Facebook's debugger. So I need the URL that is pointing to the wrong URL for the image.

**Comment by jp26jp** [comment]
Because [this URL](https://fakinthefunk.net/en/)'s image points to https://fakinthefunk.net/en/assets/fakinthefunk-social-media-preview.png. Which is the correct URL, and not the URL that you previously mentioned that it was pointing to.

**Comment by ferdesignnl** [comment]
I’ve found the issue regarding the link image-wise.

 

See attach of exporting-to-html aswell.

When I use the https://fakinthefunk.net at exporting, the widget directs to https://fakinthefunk.net/assets/

I’m now using https://fakinthefunk.net/en at exporting, so the widget directs to https://fakinthefunk.net/en/assets/

Works! =)

I think I’ve followed up your advice too literally when exporting, where u mention u should use your domain.

 

The only errors now, are attached, see pic.

Something about that Fancy / Extraneous Property + Parser Mismatched Metadata?

 

I’ve updated my Muse-file; u can download here: http://ferdesign.nl/FTF-EN-v3_j26.zip

 

 

 

Van: John R Perry [mailto:notifications@github.com] 
Verzonden: vrijdag 10 maart 2017 12:23
Aan: j26design/SEO-for-Webpages <SEO-for-Webpages@noreply.github.com>
CC: ferdesignnl <info@ferdesign.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [j26design/SEO-for-Webpages] Not able to change location Social Media Preview Image (#7)

 

You sent me 2 links to images and I'm assuming that you didn't test a link to an image in Facebook's debugger. So I need the URL that is pointing to the wrong URL for the image.

**Comment by jp26jp** [comment]
> When I use the https://fakinthefunk.net at exporting, the widget directs to https://fakinthefunk.net/assets/
> 
> I’m now using https://fakinthefunk.net/en at exporting, so the widget directs to https://fakinthefunk.net/en/assets/
So it's doing exactly what it should be doing haha.

> The only errors now, are attached, see pic.
> Something about that Fancy / Extraneous Property + Parser Mismatched Metadata?
These are bugs in Facebook's debugger. It doesn't recognize the fancy tags are but they're valid tags.
