### ISSUE TITLE
No image for Real Estate 

### ISSUE THREAD

**Issue by swflsites** [j26design/SEO-for-Webpages#9]
Hi, 

 Can you add the ability to add images to all widgets Real Estate, business, or have more options under fancy Category, not sure why on the some would show up as @webpage on the website structure. 

@type	WebPage
name	The Place at Corkscrew | Prices 239.248.0551
url	http://THEPLACE-CORKSCREW.COM/index.html

Thank you 
Lina
swflsites@gmail.com

**Comment by jp26jp** [comment]
Can you reword that? I can't quite tell what you're asking.
